services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_test
    command: bash /app/scripts/container/start_test.sh
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - PYTHONPATH=/app
    env_file:
      - .env.test